// =============================================================================
// QStore IMS V2L — Sample Seed Data
// =============================================================================
// Pre-populates the learning environment with realistic AAC Q-store data.
// Written to IndexedDB on first launch of V2L.
//
// UNIT:     1 AAC Training Unit
// CADETS:   8 (CDTs, LCPLs, CPLs, SGTs across 2 platoons)
// STAFF:    3 (OC, Training Officer, RSM)
// ITEMS:    10 inventory items
// LOANS:    2 active loans
// =============================================================================

const NOW   = new Date().toISOString();
const TODAY = NOW.slice(0, 10);
const WEEK_AGO  = new Date(Date.now() - 7  * 86400000).toISOString().slice(0, 10);
const MONTH_AGO = new Date(Date.now() - 30 * 86400000).toISOString().slice(0, 10);
const DUE_NEXT_WEEK = new Date(Date.now() + 7 * 86400000).toISOString().slice(0, 10);

export const SEED = {
  // ── Unit settings ──────────────────────────────────────────────────────────
  settings: {
    unitName:       '1 AAC Training Unit',
    unitCode:       '1 TU',
    unitState:      'QLD',
    qmName:         'Miller',
    qmRank:         'WO2-AAC',
    coName:         'Johnson',
    coRank:         'CAPT-AAC',
    categories:     ['Weapons', 'Clothing', 'Footwear', 'Equipment', 'Camping', 'Medical'],
    'ui.theme':     'dark',
  },

  // ── Inventory items ────────────────────────────────────────────────────────
  items: [
    {
      id:        'item-001',
      nsn:       '1005-66-152-6375',
      name:      'EF88 Austeyr 5.56mm',
      cat:       'Weapons',
      authQty:   10,
      onHand:    9,   // 1 on loan
      onLoan:    1,
      unsvc:     0,
      loc:       'Armoury',
      notes:     'Serial numbers recorded in armoury register',
      condition: 'Svc',
      createdAt: MONTH_AGO,
    },
    {
      id:        'item-002',
      nsn:       '8415-66-148-3951',
      name:      'Jacket DPCU',
      cat:       'Clothing',
      authQty:   20,
      onHand:    18,  // 2 on loan
      onLoan:    2,
      unsvc:     0,
      loc:       'Q-Store Bay 1',
      notes:     '',
      condition: 'Svc',
      createdAt: MONTH_AGO,
    },
    {
      id:        'item-003',
      nsn:       '8415-66-148-3952',
      name:      'Trouser DPCU',
      cat:       'Clothing',
      authQty:   20,
      onHand:    18,
      onLoan:    2,
      unsvc:     1,
      loc:       'Q-Store Bay 1',
      notes:     '1 x unserviceable (damaged knee)',
      condition: 'Svc',
      createdAt: MONTH_AGO,
    },
    {
      id:        'item-004',
      nsn:       '8430-66-143-2100',
      name:      'Boots Combat DPCU',
      cat:       'Footwear',
      authQty:   15,
      onHand:    15,
      onLoan:    0,
      unsvc:     0,
      loc:       'Q-Store Bay 2',
      notes:     'Various sizes — check sizing chart before issue',
      condition: 'Svc',
      createdAt: MONTH_AGO,
    },
    {
      id:        'item-005',
      nsn:       '8465-66-148-4001',
      name:      'Webbing DPCU',
      cat:       'Equipment',
      authQty:   12,
      onHand:    10,  // 2 on loan
      onLoan:    2,
      unsvc:     0,
      loc:       'Q-Store Bay 2',
      notes:     '',
      condition: 'Svc',
      createdAt: MONTH_AGO,
    },
    {
      id:        'item-006',
      nsn:       '8465-00-261-6838',
      name:      'Water Canteen 1L',
      cat:       'Equipment',
      authQty:   15,
      onHand:    13,  // 2 on loan
      onLoan:    2,
      unsvc:     0,
      loc:       'Q-Store Bay 2',
      notes:     '',
      condition: 'Svc',
      createdAt: MONTH_AGO,
    },
    {
      id:        'item-007',
      nsn:       '8340-66-148-4200',
      name:      'Groundsheet DPCU',
      cat:       'Camping',
      authQty:   10,
      onHand:    10,
      onLoan:    0,
      unsvc:     0,
      loc:       'Q-Store Bay 3',
      notes:     '',
      condition: 'Svc',
      createdAt: MONTH_AGO,
    },
    {
      id:        'item-008',
      nsn:       '8340-66-148-4201',
      name:      'Sleeping Bag Patrol',
      cat:       'Camping',
      authQty:   8,
      onHand:    8,
      onLoan:    0,
      unsvc:     2,
      loc:       'Q-Store Bay 3',
      notes:     '2 x U/S — zip failure',
      condition: 'Svc',
      createdAt: MONTH_AGO,
    },
    {
      id:        'item-009',
      nsn:       '8465-66-148-4300',
      name:      'Pack 90L DPCU',
      cat:       'Equipment',
      authQty:   10,
      onHand:    10,
      onLoan:    0,
      unsvc:     0,
      loc:       'Q-Store Bay 3',
      notes:     '',
      condition: 'Svc',
      createdAt: MONTH_AGO,
    },
    {
      id:        'item-010',
      nsn:       '6510-00-582-7214',
      name:      'First Field Dressing',
      cat:       'Medical',
      authQty:   25,
      onHand:    25,
      onLoan:    0,
      unsvc:     0,
      loc:       'Q-Store Medical Cabinet',
      notes:     'Check expiry dates — next review due ' + DUE_NEXT_WEEK,
      condition: 'Svc',
      createdAt: MONTH_AGO,
    },
  ],

  // ── Cadets ─────────────────────────────────────────────────────────────────
  cadets: [
    { svcNo: '8880001', rank: 'CDT',  surname: 'SMITH',    given: 'John',    plt: '1', personType: 'cadet', active: true, email: '', notes: '' },
    { svcNo: '8880002', rank: 'CDT',  surname: 'JONES',    given: 'Sarah',   plt: '1', personType: 'cadet', active: true, email: '', notes: '' },
    { svcNo: '8880003', rank: 'LCPL', surname: 'BROWN',    given: 'Michael', plt: '1', personType: 'cadet', active: true, email: '', notes: '' },
    { svcNo: '8880004', rank: 'CPL',  surname: 'WILSON',   given: 'Emma',    plt: '1', personType: 'cadet', active: true, email: '', notes: '' },
    { svcNo: '8880005', rank: 'SGT',  surname: 'TAYLOR',   given: 'David',   plt: '2', personType: 'cadet', active: true, email: '', notes: '' },
    { svcNo: '8880006', rank: 'CDT',  surname: 'ANDERSON', given: 'Lucy',    plt: '2', personType: 'cadet', active: true, email: '', notes: '' },
    { svcNo: '8880007', rank: 'CDT',  surname: 'THOMPSON', given: 'James',   plt: '2', personType: 'cadet', active: true, email: '', notes: '' },
    { svcNo: '8880008', rank: 'LCPL', surname: 'WHITE',    given: 'Olivia',  plt: '2', personType: 'cadet', active: true, email: '', notes: '' },
  ],

  // ── Staff ──────────────────────────────────────────────────────────────────
  staff: [
    { svcNo: '1110001', rank: 'CAPT-AAC', surname: 'JOHNSON', given: 'Robert',   position: 'OC',               company: '', personType: 'staff', active: true, email: '', notes: '' },
    { svcNo: '1110002', rank: 'LT-AAC',   surname: 'DAVIS',   given: 'Michelle', position: 'Training Officer',  company: '', personType: 'staff', active: true, email: '', notes: '' },
    { svcNo: '1110003', rank: 'WO2-AAC',  surname: 'MILLER',  given: 'Paul',     position: 'RSM',               company: '', personType: 'staff', active: true, email: '', notes: '' },
  ],

  // ── Active loans ───────────────────────────────────────────────────────────
  loans: [
    // Loan 1 — CDT Smith: Webbing + Canteen (weekly training issue)
    {
      ref:           'L-0001',
      borrowerSvc:   '8880001',
      borrowerName:  'CDT Smith J.',
      purpose:       'Weekly Training',
      issueDate:     WEEK_AGO,
      dueDate:       DUE_NEXT_WEEK,
      itemId:        'item-005',
      itemName:      'Webbing DPCU',
      nsn:           '8465-66-148-4001',
      qty:           1,
      condition:     'Svc',
      remarks:       'Issued for Tuesday night parade',
      returned:      false,
      returnDate:    null,
      returnCondition: null,
      issuedBy:      'WO2-AAC Miller',
    },
    {
      ref:           'L-0002',
      borrowerSvc:   '8880001',
      borrowerName:  'CDT Smith J.',
      purpose:       'Weekly Training',
      issueDate:     WEEK_AGO,
      dueDate:       DUE_NEXT_WEEK,
      itemId:        'item-006',
      itemName:      'Water Canteen 1L',
      nsn:           '8465-00-261-6838',
      qty:           1,
      condition:     'Svc',
      remarks:       'Issued with webbing set',
      returned:      false,
      returnDate:    null,
      returnCondition: null,
      issuedBy:      'WO2-AAC Miller',
    },
    // Loan 2 — CPL Wilson: EF88 (range practice)
    {
      ref:           'L-0003',
      borrowerSvc:   '8880004',
      borrowerName:  'CPL Wilson E.',
      purpose:       'Range Practice',
      issueDate:     TODAY,
      dueDate:       TODAY,
      itemId:        'item-001',
      itemName:      'EF88 Austeyr 5.56mm',
      nsn:           '1005-66-152-6375',
      qty:           1,
      condition:     'Svc',
      remarks:       'SN: AAC-24-0047 — Cadet is qualified RASA',
      returned:      false,
      returnDate:    null,
      returnCondition: null,
      issuedBy:      'CAPT-AAC Johnson',
    },
    // Loan 3 — SGT Taylor: Jacket + Trouser + Webbing + Canteen (field exercise)
    {
      ref:           'L-0004',
      borrowerSvc:   '8880005',
      borrowerName:  'SGT Taylor D.',
      purpose:       'Field Exercise',
      issueDate:     TODAY,
      dueDate:       DUE_NEXT_WEEK,
      itemId:        'item-002',
      itemName:      'Jacket DPCU',
      nsn:           '8415-66-148-3951',
      qty:           1,
      condition:     'Svc',
      remarks:       'FEX IRONBARK — returns Mon',
      returned:      false,
      returnDate:    null,
      returnCondition: null,
      issuedBy:      'WO2-AAC Miller',
    },
    {
      ref:           'L-0005',
      borrowerSvc:   '8880005',
      borrowerName:  'SGT Taylor D.',
      purpose:       'Field Exercise',
      issueDate:     TODAY,
      dueDate:       DUE_NEXT_WEEK,
      itemId:        'item-003',
      itemName:      'Trouser DPCU',
      nsn:           '8415-66-148-3952',
      qty:           1,
      condition:     'Svc',
      remarks:       'FEX IRONBARK — returns Mon',
      returned:      false,
      returnDate:    null,
      returnCondition: null,
      issuedBy:      'WO2-AAC Miller',
    },
    {
      ref:           'L-0006',
      borrowerSvc:   '8880005',
      borrowerName:  'SGT Taylor D.',
      purpose:       'Field Exercise',
      issueDate:     TODAY,
      dueDate:       DUE_NEXT_WEEK,
      itemId:        'item-005',
      itemName:      'Webbing DPCU',
      nsn:           '8465-66-148-4001',
      qty:           1,
      condition:     'Svc',
      remarks:       'FEX IRONBARK — returns Mon',
      returned:      false,
      returnDate:    null,
      returnCondition: null,
      issuedBy:      'WO2-AAC Miller',
    },
    {
      ref:           'L-0007',
      borrowerSvc:   '8880005',
      borrowerName:  'SGT Taylor D.',
      purpose:       'Field Exercise',
      issueDate:     TODAY,
      dueDate:       DUE_NEXT_WEEK,
      itemId:        'item-006',
      itemName:      'Water Canteen 1L',
      nsn:           '8465-00-261-6838',
      qty:           1,
      condition:     'Svc',
      remarks:       'FEX IRONBARK — returns Mon',
      returned:      false,
      returnDate:    null,
      returnCondition: null,
      issuedBy:      'WO2-AAC Miller',
    },
  ],
};
